import type { Metadata } from 'next'
import './globals.css'
import './styles/loading-style.css'
import './styles/underline-style.css'
import Header from './layouts/Header'
import { MantineProvider } from '@mantine/core';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <MantineProvider>
          <Header />
          <main className='w-full min-h-screen gradient_background pt-10 md:pt-28'>
            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  )
}
